service: lambda-sample
frameworkVersion: '2'

custom:
  prune:
    automatic: true
    number: 10
  common: ${file(./env/common.json)}
  env: ${file(./env/${opt:stage,'local'}.json)}

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: ${self:custom.env.REGION}
  memorySize: 256
  timeout: 60
  deploymentBucket:
    name: kakaowebtoon-serverless-deploys-sandbox
  role: ${self:custom.env.ROLE}
  vpc:
    securityGroupIds:
      - sg-0fcc53d5d6d7f6013
    subnetIds:
      - subnet-095ee8c4b19f948c5
      - subnet-0140194953048852d
      - subnet-065207e4ee21f3ea7
  environment:
    ALREADY_READ_DYNAMODB_TABLE: ${self:custom.env.ALREADY_READ_DYNAMODB_TABLE}
    TIMEZONE_OFFSET: ${self:custom.env.TIMEZONE_OFFSET}
  logRetentionInDays: ${self:custom.env.LOG_RETENTION, 3}

functions:
  main:
    handler: handler.main
