service: lambda-multipart-test
frameworkVersion: '2'

custom:
  prune:
    automatic: true
    number: 10
  env: ${file(./env/${opt:stage,'local'}.json)}

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ap-northeast-2
  profile: kwtoon
  memorySize: 256
  timeout: 60
  deploymentBucket:
    name: ${self:custom.env.DEPLOYMENT_BUCKET}
  role: ${self:custom.env.ROLE}
  vpc:
    securityGroupIds:
      - ${self:custom.env.SECURITY_GROUP}
    subnetIds:
      - ${self:custom.env.SUBNET_1}
      - ${self:custom.env.SUBNET_2}
      - ${self:custom.env.SUBNET_3}
functions:
  main:
    handler: handler.main
